### ISSUE TITLE
response.Zi object is no longer exists in response

### ISSUE THREAD

**Issue by Edward101701** [anthonyjgrove/react-google-login#298]
I have code snippet in my application:

`<GoogleLogin
    clientId={GOOGLE_CLIENT_ID}
    onSuccess={onSuccess}
    onFailure={onFailure}
/>`

Previously i read **response.Zi.id_token**, but today i figured out that **Zi** object no more exists and login feature of my application became broken. 

![image](https://user-images.githubusercontent.com/12069900/74530384-8ebe0b80-4f32-11ea-8711-ea89650e8a3e.png)

After debugging i saw that there is a new object **tokenObj** with **id_token** field. It looks like about i need, but i have a question how this breaking change became possible ?

**Comment by ivowiblo** [comment]
Found the same issue, but I see a field Zw instead.

**Comment by ernestognw** [comment]
Same here.

Seems there is not an issue of this package since there are no breaking changes in previous commits. I think is more a Google update but I couldn't find recent updates to the Javascript API or the google auth docs. 

I'm gonna add the Zi object manually just to fix the breaking change for those who relies on the previous version, and update the docs to use the tokenObj

**Comment by anthonyjgrove** [comment]
This isn't the first time google has changed the key the token is on, that is why i normalized it out into the tokenObj.  I suggest switching to use the tokenObj or do `res.getAuthResponse()` which is what google expects you to do.  Given the key the token is on has changed before so it is likely meant to be private.  The Readme will need to be updated to reflect this.
