### ISSUE TITLE
onAutoLoadFinished required in Readonly<GoogleLoginProps>

### ISSUE THREAD

**Issue by altimas** [anthonyjgrove/react-google-login#333]
<img width="923" alt="Screen Shot 2020-05-12 at 12 30 56 PM" src="https://user-images.githubusercontent.com/10324294/81726205-a1ba7c00-944c-11ea-8b49-4edab05bfadf.png">

Upgraded from 5.1.14 to 5.1.17 and it broke during the Typescript compile with the above error.

But it doesn't show this as a required Prop in the ReadMe.

**Comment by puku0x** [comment]
I think it should be optional because `useGoogleLogin()` which is used in `<GoogleLogin />` has default value.
https://github.com/anthonyjgrove/react-google-login/blob/master/src/use-google-login.js#L6-L9

According to the implementation of the hook, all these callbacks can be optional.
- onSuccess
- onAutoLoadFinished
- onRequest
- onFailure
